# ~/.config/kitty/kitty.conf

# ── COLORI PYWAL ───────────────────────────────────────────────────────
include ~/.cache/wal/colors-kitty.conf

# ── FONT ───────────────────────────────────────────────────────────────
font_family     DepartureMono Nerd Font Mono
bold_font       auto
italic_font     auto
bold_italic_font auto
font_size       14.0
#font_family      JetBrainsMono Nerd Font Mono
# ── CURSORE ────────────────────────────────────────────────────────────
cursor_shape               beam
cursor_beam_thickness      1.5
cursor_blink_interval      0.5
cursor_stop_blinking_after 10.0
# Scia del cursore (versione kitty >= 0.36)
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
# ── TRASPARENZA ────────────────────────────────────────────────────────
#background_opacity 0.85
#dynamic_background_opacity yes

# ── PADDING E LAYOUT ───────────────────────────────────────────────────
window_padding_width 10



# ── ANIMAZIONI ─────────────────────────────────────────────────────────
# Velocità di rendering (più alto = più fluido)
repaint_delay    8
input_delay      2
sync_to_monitor  yes

# ── MOUSE ──────────────────────────────────────────────────────────────
mouse_hide_wait              2.0
select_by_word_characters    :@-./_~?&=%+#~

# ── SCROLLING ──────────────────────────────────────────────────────────
scrollback_lines         10000
wheel_scroll_multiplier  5.0
touch_scroll_multiplier  1.0
