#!/bin/bash
# Legge i colori pywal e aggiorna GTK, Qt, Hyprland, Mako

WAL="$HOME/.cache/wal/colors"
[[ ! -f "$WAL" ]] && echo "Errore: pywal non ha ancora generato i colori." && exit 1

mapfile -t C < "$WAL"
c0="${C[0]#\#}"; c1="${C[1]#\#}"; c2="${C[2]#\#}"; c3="${C[3]#\#}"
c4="${C[4]#\#}"; c5="${C[5]#\#}"; c6="${C[6]#\#}"; c7="${C[7]#\#}"

# Anche in formato #RRGGBB per GTK/CSS
h0="#${c0}"; h1="#${c1}"; h2="#${c2}"; h3="#${c3}"
h4="#${c4}"; h5="#${c5}"; h6="#${c6}"; h7="#${c7}"

# ── 1. Hyprland colors.conf ──────────────────────────────────────────
cat > ~/.config/hypr/colors.conf << EOF
# generato da pywal - non modificare manualmente
\$color0 = rgb(${c0})
\$color1 = rgb(${c1})
\$color2 = rgb(${c2})
\$color3 = rgb(${c3})
\$color4 = rgb(${c4})
\$color5 = rgb(${c5})
\$color6 = rgb(${c6})
\$color7 = rgb(${c7})

\$active_border   = rgba(${c1}ff) rgba(${c2}ff) 45deg
\$inactive_border = rgba(${c0}aa)
EOF

# ── 2. GTK3 colori (gtk.css) ─────────────────────────────────────────
mkdir -p ~/.config/gtk-3.0
cat > ~/.config/gtk-3.0/gtk.css << EOF
@define-color accent_color ${h1};
@define-color accent_bg_color ${h1};
@define-color accent_fg_color ${h7};
@define-color window_bg_color ${h0};
@define-color window_fg_color ${h7};
@define-color view_bg_color ${h0};
@define-color view_fg_color ${h7};
@define-color headerbar_bg_color ${h0};
@define-color sidebar_bg_color ${h0};
EOF

# ── 3. GTK4 colori (gtk.css) ─────────────────────────────────────────
mkdir -p ~/.config/gtk-4.0
cp ~/.config/gtk-3.0/gtk.css ~/.config/gtk-4.0/gtk.css

# ── 4. Kvantum (Qt) ──────────────────────────────────────────────────
mkdir -p ~/.config/Kvantum/PywalTheme
cat > ~/.config/Kvantum/PywalTheme/PywalTheme.kvconfig << EOF
[%General]
author=pywal-auto
comment=Generated by wal2all.sh

[PanelButtonCommand]
frame=true
frame.element=button
interior=true
interior.element=button

[Window]
interior.element=window
EOF

# Colori Kvantum via kvantum colors file
cat > ~/.config/Kvantum/PywalTheme/PywalTheme.colors << EOF
[ColorScheme]
active_colors=${h7}, ${h0}, ${h1}, ${h2}, ${h0}, ${h0}, ${h7}, ${h7}, ${h7}, ${h0}, ${h0}, ${h1}, ${h1}, ${h7}, ${h1}, ${h0}, ${h7}, ${h1}, ${h5}, ${h0}, ${h1}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}
disabled_colors=${h7}, ${h0}, ${h1}, ${h2}, ${h0}, ${h0}, ${h7}, ${h7}, ${h7}, ${h0}, ${h0}, ${h1}, ${h1}, ${h7}, ${h1}, ${h0}, ${h7}, ${h1}, ${h5}, ${h0}, ${h1}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}
inactive_colors=${h7}, ${h0}, ${h1}, ${h2}, ${h0}, ${h0}, ${h7}, ${h7}, ${h7}, ${h0}, ${h0}, ${h1}, ${h1}, ${h7}, ${h1}, ${h0}, ${h7}, ${h1}, ${h5}, ${h0}, ${h1}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}, ${h0}
EOF

kvantummanager --set PywalTheme 2>/dev/null

# ── 5. Mako (notifiche) ───────────────────────────────────────────────
SWAYNC_CSS="$HOME/.config/swaync/style.css"
if [[ -f "$SWAYNC_CSS" ]]; then
    SWAYNC_STYLE=$(cat "$SWAYNC_CSS")
    cat > "$SWAYNC_CSS" << EOF
/* ── VARIABILI PYWAL - generato automaticamente ── */
@define-color color0 ${h0};
@define-color color1 ${h1};
@define-color color2 ${h2};
@define-color color3 ${h3};
@define-color color4 ${h4};
@define-color color5 ${h5};
@define-color color6 ${h6};
@define-color color7 ${h7};

$(echo "$SWAYNC_STYLE" | grep -v "@define-color\|@import")
EOF
    swaync-client --reload-css 2>/dev/null
fi
# Rigenera tema GTK con wpgtk
wpg -s "$(cat ~/.cache/current_wallpaper)" -n 2>/dev/null
gsettings set org.gnome.desktop.interface gtk-theme 'FlatColor'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
# ── 6. Ricarica Hyprland ──────────────────────────────────────────────
hyprctl reload 2>/dev/null

echo "✓ wal2all.sh completato — tutti i temi aggiornati"

