# generato da pywal - non modificare manualmente
$color0 = rgb(0B0814)
$color1 = rgb(2D304A)
$color2 = rgb(1B4B50)
$color3 = rgb(564B51)
$color4 = rgb(AD3342)
$color5 = rgb(968272)
$color6 = rgb(28668D)
$color7 = rgb(92dbca)

$active_border   = rgba(2D304Aff) rgba(1B4B50ff) 45deg
$inactive_border = rgba(0B0814aa)
